name: call-deploy-book

on:
  push:
    branches:
    - '**'
    paths:
    - book/**
    - requirements.txt
    - .github/workflows/call-deploy-book.yml
  workflow_dispatch:

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    uses: TeachBooks/deploy-book-workflow/.github/workflows/deploy-book.yml@v1
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
